// <auto-generated />
namespace ProgSolutions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Student_6DB3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_6DB3));
        
        string IMigrationMetadata.Id
        {
            get { return "201903090738131_Student_6DB3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
